# permissions for end users to edit cephrbdstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cephrbdstorage-editor-role
rules:
- apiGroups:
  - yamecloud.io
  resources:
  - cephrbdstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yamecloud.io
  resources:
  - cephrbdstorages/status
  verbs:
  - get
