
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - yamecloud.io
  resources:
  - cephrbdstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yamecloud.io
  resources:
  - cephrbdstorages/status
  verbs:
  - get
  - patch
  - update
