apiVersion: yamecloud.io/v1
kind: CephRBDStorage
metadata:
  name: kube-ceph-rbd-storage
  namespace: kube-system
spec:
  provisioner: ceph.com/rbd
  parameters:
    adminId: admin
    adminSecretValue: ceph-admin-secret-value
    imageFeatures: layering
    imageFormat: '2'
    monitors: '10.200.45.30:6789,10.200.45.31:6789,10.200.45.32:6789'
    pool: kube
    userId: kube
    userSecretValue: ceph-kube-secret-value
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
